### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by MoonShadowIllusion** [Akka0/Iridium-NG#3]
packetIds.json, Keys.json 和 proto/ 是什么，该在哪获取

**Comment by WorldEndSukaSuka** [comment]
同问packetIds.json, Keys.json现在在哪里弄

**Comment by Akka0** [comment]
目前不支持2.8+
proto 可以在此处获取：https://github.com/Sorapointa/Sorapointa-Protos

**Comment by Winter-is-comingXK** [comment]
> 目前不支持2.8+ proto 可以在此处获取：https://github.com/Sorapointa/Sorapointa-Protos

能提供编译好的包吗

**Comment by Winter-is-comingXK** [comment]
能提供已经编译好的吗
